dist: trusty
language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts: hive-engine.com
- provider: script
  skip_cleanup: true
  script: cd $TRAVIS_BUILD_DIR/dist && rsync -auvhp --delete --quiet ./ $REMOTE_USER@$HOST:hive-engine
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -auvhp --delete --quiet ./ $REMOTE_USER@$HOST:qa.hive-engine
  on:
    branch: develop
before_install:
- openssl aes-256-cbc -K $encrypted_134e9820d8ee_key -iv $encrypted_134e9820d8ee_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 400 ./deploy_rsa
- ssh-add ./deploy_rsa
- ssh -i ./deploy_rsa $REMOTE_USER@$HOST pwd

